#include "test.h"

// Medium sized segment test

// lorem ipsum in .rodata
const char lorem1[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu gravida magna, vitae pretium risus. Duis risus magna, hendrerit sit amet sagittis in, auctor eu massa. Fusce ut hendrerit mi, ac efficitur magna. Nulla nec mauris nec erat commodo sollicitudin ac id leo. In viverra dignissim libero, at dignissim sem. Nullam gravida ante vitae lorem pellentesque consequat. Ut a sollicitudin lorem, vitae condimentum augue. Morbi id varius purus. Proin aliquam euismod nibh sit amet viverra.\n"
"\n"
"Pellentesque finibus lorem vitae placerat consequat. Proin iaculis lobortis elit, a malesuada velit tincidunt eget. Aenean quis sodales erat. Maecenas faucibus ex ante, vitae vulputate quam eleifend in. Curabitur tincidunt tortor quam, non molestie magna porta a. Suspendisse potenti. Vestibulum vel tincidunt risus. Suspendisse turpis ex, eleifend non felis ac, mollis scelerisque libero. Vivamus sit amet fringilla lorem.\n"
"\n"
"Donec interdum vulputate lectus, nec varius mauris cursus efficitur. Aenean accumsan pellentesque sem fringilla euismod. Donec sodales vel dui pharetra condimentum. Pellentesque id imperdiet nulla. Quisque ultricies tincidunt velit nec faucibus. Duis fermentum, sapien eu varius luctus, velit augue vulputate arcu, non dignissim metus orci at diam. Proin augue quam, congue eget imperdiet nec, dapibus eu quam. Pellentesque semper facilisis ex. Integer ac dictum est, sit amet tincidunt erat. Pellentesque suscipit blandit sem, at scelerisque nibh commodo id. Nulla euismod dui nec erat faucibus, non ultrices ligula consequat. Donec ac sollicitudin est. Etiam accumsan diam id massa consequat, sit amet condimentum velit suscipit. Aliquam id imperdiet magna. Duis imperdiet condimentum tincidunt. In tortor nisl, ornare sit amet tristique a, feugiat non libero.\n"
"\n"
"Vivamus feugiat massa est, non imperdiet ex pretium quis. Morbi nisi enim, sollicitudin sed justo ac, tincidunt hendrerit ante. Sed accumsan dapibus sem, quis aliquam tellus rhoncus eleifend. Nunc at sem sed massa feugiat mattis. Sed imperdiet rutrum dictum. Mauris turpis elit, pretium at imperdiet ac, scelerisque at tortor. Donec laoreet elementum nibh nec lobortis.\n"
"\n"
"Nam varius urna sed ligula pretium, non dictum tellus iaculis. Integer ut velit eget lacus tincidunt consequat. Vivamus et aliquam felis. Ut a nulla tellus. Sed efficitur eu purus at tincidunt. Aliquam luctus pretium congue. Vivamus sit amet ex sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante eu purus interdum finibus id eu mauris. Nunc erat velit, varius vel semper tristique, commodo eget quam. Proin at fringilla orci. Nulla quis viverra magna. Integer sed posuere turpis.\n"
"\n"
"Cras at elementum libero, malesuada semper urna. Fusce accumsan erat ut magna faucibus egestas nec eget elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras lorem nulla, malesuada et neque sit amet, ullamcorper fringilla dui. Aenean fringilla sem in hendrerit convallis. Vivamus lacus orci, cursus ut tellus eu, auctor elementum urna. Vivamus non diam ut nulla blandit tempor. Curabitur vitae aliquam quam. Nunc sollicitudin ipsum enim, a accumsan lorem dictum eget. Donec pellentesque metus id mi maximus efficitur. Nunc quis sapien consectetur arcu tincidunt lacinia a sed felis.\n"
"\n"
"Donec hendrerit eget diam a pellentesque. Nulla mi erat, tincidunt nec turpis vitae, lacinia auctor justo. Phasellus in erat nibh. Quisque suscipit cursus augue, sed semper augue porta ut. Nunc nunc nisl, consequat non condimentum eu, tincidunt quis massa. In at tortor ac enim lobortis viverra eget sed libero. Integer fringilla lorem ligula, vel ultrices lorem efficitur vitae. Phasellus a rutrum leo. Quisque iaculis elit vel ante placerat facilisis. In nec aliquet dui. Praesent augue velit, scelerisque eget ultrices nec, consectetur vitae nisi.\n"
"\n"
"Ut leo enim, sodales sed purus laoreet, convallis suscipit quam. Vivamus placerat sem non nibh venenatis pulvinar. Cras luctus quam in pharetra sodales. Vestibulum venenatis vulputate dui, vel semper lacus condimentum nec. Mauris nec lectus fermentum, consequat augue eu, placerat libero. Pellentesque tempor urna dolor, non commodo est venenatis at. Vestibulum volutpat enim quis viverra pellentesque. Nam rhoncus vel metus id dapibus. Suspendisse suscipit fringilla augue, nec interdum risus gravida ut. Cras vehicula consectetur metus vitae posuere.\n"
"\n"
"Duis a dictum mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed eu placerat tortor, in fringilla nisl. Nunc commodo at magna eget laoreet. Ut porta varius ex, sed aliquet tellus dignissim ut. Nulla rhoncus dolor eget nisl consectetur dictum at et ante. Nam lobortis, magna at faucibus suscipit, lacus magna placerat risus, quis placerat justo neque sed diam. Maecenas cursus arcu maximus magna scelerisque consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam non ante auctor, tincidunt erat sit amet, semper justo. Nullam sagittis suscipit nunc, et eleifend felis ultrices eu. Mauris lacinia porta urna ut laoreet. Fusce convallis justo eros, malesuada faucibus enim auctor in. Morbi convallis lectus nec dui laoreet varius. Integer velit sem, mollis vel facilisis in, fringilla mattis augue.\n"
"\n"
"Quisque at elit nec enim hendrerit cursus. Maecenas elit tellus, elementum in felis vel, efficitur efficitur diam. Ut vel leo at justo euismod tincidunt. Nullam pretium rhoncus sagittis. Nullam lectus tellus, vestibulum ut mi sit amet, ornare viverra purus. Fusce ullamcorper ornare viverra. Donec feugiat, sapien nec euismod bibendum, nunc mi mattis dolor, eu pharetra tellus lorem fringilla odio. Vestibulum lacus turpis, feugiat a libero a, malesuada viverra nulla.\n"
"\n"
"Nam nec pharetra ex, ut pulvinar felis. Ut est purus, volutpat vitae tristique in, mollis at massa. Proin vel suscipit neque. Quisque porttitor eleifend tempor. Cras accumsan neque id elementum porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent at elit odio. Cras in commodo erat. Quisque eget interdum justo. Praesent viverra massa a nisi sodales lacinia quis eu erat. Vestibulum semper placerat mauris pretium scelerisque. Praesent non diam euismod, elementum purus eu, congue leo. Phasellus bibendum purus id luctus euismod. Nunc egestas nunc id augue sollicitudin, a convallis nunc malesuada. Quisque ut ipsum libero. Maecenas rhoncus venenatis dui.\n"
"\n"
"Morbi ullamcorper pretium est commodo ultrices. Pellentesque cursus gravida pellentesque. Ut finibus porta auctor. Aenean vehicula, diam sed luctus vestibulum, augue leo viverra nisl, vitae faucibus lacus leo sit amet massa. Sed scelerisque, neque euismod sodales viverra, nunc felis egestas neque, sed fermentum dolor velit eget dolor. Aliquam at ipsum dapibus, volutpat tellus sit amet, malesuada lacus. Nullam ut tellus in elit dapibus sollicitudin. Ut semper enim sapien, eu mattis lectus luctus ut. Nulla dapibus, purus vel porta interdum, nunc diam consequat felis, in hendrerit felis sapien vitae elit. Curabitur finibus faucibus massa non ornare.\n"
"\n"
"Cras nec mattis neque. Morbi non nulla in sapien condimentum consectetur sit amet nec nisi. Cras interdum nisl sem, et ullamcorper odio tristique ac. Maecenas pharetra diam et orci vestibulum, eget imperdiet leo condimentum. Phasellus mattis urna at nibh rhoncus ultricies. Nullam nulla sem, dictum non efficitur eget, pellentesque nec diam. Nunc tincidunt ut dolor non fermentum. In hac habitasse platea dictumst. Sed laoreet felis id libero lacinia fringilla vitae quis est. Donec enim orci, imperdiet eget leo non, luctus vehicula nunc. Phasellus lorem mauris, convallis non aliquam sed, aliquam nec lacus.\n"
"\n"
"Morbi pretium ante vel interdum ultrices. Aliquam sed dolor at dui vestibulum iaculis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at ornare mi. Donec at ipsum eget orci ultrices tempus id sit amet mi. Cras id condimentum mauris. Suspendisse potenti. Integer eget suscipit ipsum. Phasellus varius dolor nec tellus congue, quis convallis nunc eleifend.\n"
"\n"
"Sed consequat cursus sem, eu lacinia augue faucibus eget. Donec eu metus ante. Quisque sodales dui in velit elementum gravida. Nullam in est eget odio pellentesque consequat id lacinia felis. Integer ante quam, consequat id elit quis, malesuada efficitur enim. Nunc ultrices tristique nibh, id condimentum nisi commodo non. Vivamus rutrum libero ac leo bibendum, quis condimentum arcu dignissim. Quisque at ipsum at ipsum facilisis pharetra eu nec odio. Proin convallis elit orci, a sagittis turpis ullamcorper ut. Donec pretium tortor ut tellus suscipit ornare tempus ac lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc feugiat mauris sit amet diam tincidunt, nec gravida enim placerat. Morbi ac accumsan diam.\n"
"\n"
"Duis finibus sapien vel eros lacinia, ac aliquet sem volutpat. Curabitur eleifend, purus a auctor consequat, ligula massa efficitur nisl, et pulvinar risus enim eu orci. Suspendisse porttitor bibendum nibh, non ultrices velit. Vivamus luctus ipsum ac tristique malesuada. Quisque luctus nisl erat, sed ullamcorper diam auctor et. Etiam lectus nulla, convallis vitae finibus et, scelerisque ut justo. Etiam dui est, euismod vitae viverra quis, vestibulum et velit. Duis vel nisi sit amet quam iaculis tempus. Aliquam efficitur et eros et consequat.\n"
"\n"
"Quisque tortor velit, elementum a eleifend nec, bibendum in nunc. Fusce elit lorem, imperdiet ut sodales eget, lobortis ultricies elit. Suspendisse ultrices a tellus vel pretium. Mauris egestas posuere risus at bibendum. Sed eu arcu imperdiet, finibus ligula consectetur, rutrum nunc. Curabitur auctor nisl lacus, vitae aliquet augue malesuada sed. In metus eros, mattis in lorem nec, placerat vulputate urna. In eu ligula ultricies, rutrum quam tristique, condimentum massa. Quisque rhoncus consequat ante eu mattis. Aliquam cursus arcu at metus hendrerit, eu finibus magna molestie. Donec consectetur nunc nec sagittis porttitor. Suspendisse potenti. Donec malesuada sem quis diam tristique, viverra consectetur ante pretium. Nullam varius justo a est hendrerit, eu rhoncus eros semper.\n"
"\n"
"Vivamus turpis diam, eleifend in augue ut, placerat faucibus turpis. Nunc aliquam, sem eu efficitur dignissim, velit sapien volutpat turpis, nec posuere ligula tortor ut ipsum. Quisque viverra ex eu scelerisque bibendum. Etiam lobortis est ac elementum volutpat. Fusce turpis sem, hendrerit non lobortis et, mollis a dui. Cras vel risus tincidunt est bibendum pulvinar quis eget lorem. Aliquam bibendum blandit molestie. Etiam nec interdum odio, vel vestibulum arcu. Fusce tempor mi id mauris placerat, non sollicitudin odio aliquet. Nam malesuada suscipit tortor, quis sollicitudin sapien volutpat a. Etiam dignissim volutpat erat, in commodo tellus tempor in. Vivamus urna enim, consequat vel nibh euismod, placerat laoreet tortor. Maecenas in molestie augue, nec gravida sem. Vivamus in mollis mauris. Sed feugiat neque eu odio euismod, sit amet sodales est iaculis. Mauris non pellentesque augue.\n"
"\n"
"Pellentesque augue purus, semper ac scelerisque vel, volutpat eu mi. Quisque tincidunt rutrum lorem, id porttitor nulla eleifend mattis. Integer nec est quis felis mattis elementum eget id velit. Nulla nec felis vitae arcu tincidunt convallis quis vel eros. Sed rhoncus semper magna, sed sollicitudin ex facilisis eu. Morbi commodo, metus et gravida bibendum, leo tellus facilisis leo, commodo eleifend libero odio lacinia odio. Fusce vel lacus risus. Nullam est arcu, suscipit eget mattis ac, viverra non orci.\n"
"\n"
"In faucibus lorem fringilla metus cursus, ac efficitur neque varius. Donec diam sem, blandit ac orci pretium, ultricies pharetra tellus. Mauris pharetra blandit ligula. Suspendisse varius, nisi sit amet ultrices lacinia, augue nisl cursus libero, eget venenatis urna ante eu ex. Duis ut purus porta dui convallis blandit. Vivamus mollis facilisis mi, quis imperdiet sem malesuada eu. Sed leo arcu, suscipit non mi sit amet, auctor tempor tellus. Suspendisse id viverra risus.\n"
"\n"
"Aenean in ullamcorper dui. Integer sollicitudin commodo lectus, quis consequat velit commodo id. Vestibulum auctor eros quis nisl faucibus, varius congue mi sollicitudin. Vivamus auctor libero ut nulla lobortis gravida. Praesent et ornare orci. Pellentesque ut viverra odio. In hac habitasse platea dictumst. Sed quis libero ac arcu ultrices molestie. Sed fermentum arcu ante, eget elementum metus feugiat non. Donec ornare egestas tellus quis elementum. Maecenas quis commodo tortor. Donec sodales commodo leo, vitae elementum risus dignissim vel. Phasellus at sapien vitae nisl molestie blandit. Nulla ultrices dapibus dignissim. Vivamus at ex eu dolor faucibus iaculis. Cras congue bibendum risus at rhoncus.\n"
"\n"
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis sit amet quam magna. In ut sagittis est. Mauris sit amet sem sed nulla dictum varius sit amet vitae nisl. Phasellus scelerisque pharetra tristique. Mauris in euismod libero. Morbi suscipit egestas nisl nec sollicitudin. Fusce dapibus, urna ut varius dignissim, tellus ligula auctor nulla, ac semper eros felis sodales mauris. Donec quis mollis magna. Phasellus accumsan ligula nec lacus hendrerit, quis bibendum quam ullamcorper. Proin egestas cursus egestas. Cras varius sapien mauris, et sollicitudin libero tempus ut. Fusce aliquam nisi in feugiat facilisis. Ut mattis luctus mattis.\n"
"\n"
"Maecenas in diam rhoncus, luctus nisl nec, scelerisque magna. Aliquam vulputate orci magna, a suscipit neque ultrices eget. Praesent sodales pharetra mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque accumsan porta interdum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In gravida tempus semper. Nullam at lectus eget justo maximus viverra vitae quis lectus. Nullam nulla libero, sodales eu libero ut, posuere tempor turpis.\n"
"\n"
"Suspendisse at velit at nibh tristique eleifend sit amet sed elit. Nam diam lacus, varius eget scelerisque in, volutpat et leo. Pellentesque nec laoreet eros. Nullam imperdiet tellus nec lorem faucibus ullamcorper. Suspendisse tincidunt vulputate dignissim. Nullam pharetra libero turpis, gravida efficitur augue euismod eu. Aenean dui ipsum, cursus eget pulvinar pharetra, condimentum sed libero. Aenean diam nisl, imperdiet eu faucibus eu, faucibus non eros. Mauris eu nulla rutrum, consequat urna ac, auctor leo. Cras luctus, odio eget suscipit fermentum, elit orci facilisis ex, gravida tempor lacus augue sit amet libero. Suspendisse posuere ante sit amet tellus condimentum vestibulum. Aliquam efficitur, lectus vitae interdum scelerisque, neque libero blandit velit, sed placerat ipsum est non erat. Duis eleifend iaculis ultrices. Proin pharetra neque interdum, volutpat risus hendrerit, varius ante.\n"
"\n"
"Ut dignissim vulputate nulla dapibus dapibus. Praesent dapibus nisi vitae diam egestas gravida. Vestibulum quis justo mattis, fermentum quam eget, porta nunc. Nunc elit libero, ultrices ut ante at, maximus imperdiet enim. Suspendisse malesuada, arcu non ornare scelerisque, orci quam hendrerit lacus, nec maximus neque ante a magna. Quisque pulvinar maximus nisi eget iaculis. Vivamus sed sem at nulla dignissim posuere id at purus. Pellentesque ultricies leo ut sagittis suscipit. Morbi id eros lobortis, pellentesque neque ut, efficitur lorem. Ut ac elit tincidunt, blandit felis in, ultricies libero. Fusce vel egestas mi.\n"
"\n"
"Sed eget lorem tincidunt, dapibus metus sed, luctus erat. Phasellus eget arcu nec libero volutpat sollicitudin ac id justo. Aliquam non facilisis tellus. Fusce dictum, leo a efficitur ultrices, dolor magna ullamcorper elit, eu vulputate felis leo in tellus. Nulla cursus urna molestie, sodales elit non, ultrices mi. Nulla feugiat ex id consequat aliquet. In volutpat nunc tortor, vitae sagittis lacus pellentesque finibus. Donec a libero quis purus sodales viverra. Nam id urna a.";

// Success and error messages
const char success_msg[] = "Success: strings match!\n";
const char error_msg[] = "Error: string mismatch!\n";

// Another array in .data (to offset lorem2)
char data_to_offset_lorem2[32] = "This is to offset lorem2 string";

// Modifiable version of same lorem ipsum string as lorem1
char lorem2[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu gravida magna, vitae pretium risus. Duis risus magna, hendrerit sit amet sagittis in, auctor eu massa. Fusce ut hendrerit mi, ac efficitur magna. Nulla nec mauris nec erat commodo sollicitudin ac id leo. In viverra dignissim libero, at dignissim sem. Nullam gravida ante vitae lorem pellentesque consequat. Ut a sollicitudin lorem, vitae condimentum augue. Morbi id varius purus. Proin aliquam euismod nibh sit amet viverra.\n"
"\n"
"Pellentesque finibus lorem vitae placerat consequat. Proin iaculis lobortis elit, a malesuada velit tincidunt eget. Aenean quis sodales erat. Maecenas faucibus ex ante, vitae vulputate quam eleifend in. Curabitur tincidunt tortor quam, non molestie magna porta a. Suspendisse potenti. Vestibulum vel tincidunt risus. Suspendisse turpis ex, eleifend non felis ac, mollis scelerisque libero. Vivamus sit amet fringilla lorem.\n"
"\n"
"Donec interdum vulputate lectus, nec varius mauris cursus efficitur. Aenean accumsan pellentesque sem fringilla euismod. Donec sodales vel dui pharetra condimentum. Pellentesque id imperdiet nulla. Quisque ultricies tincidunt velit nec faucibus. Duis fermentum, sapien eu varius luctus, velit augue vulputate arcu, non dignissim metus orci at diam. Proin augue quam, congue eget imperdiet nec, dapibus eu quam. Pellentesque semper facilisis ex. Integer ac dictum est, sit amet tincidunt erat. Pellentesque suscipit blandit sem, at scelerisque nibh commodo id. Nulla euismod dui nec erat faucibus, non ultrices ligula consequat. Donec ac sollicitudin est. Etiam accumsan diam id massa consequat, sit amet condimentum velit suscipit. Aliquam id imperdiet magna. Duis imperdiet condimentum tincidunt. In tortor nisl, ornare sit amet tristique a, feugiat non libero.\n"
"\n"
"Vivamus feugiat massa est, non imperdiet ex pretium quis. Morbi nisi enim, sollicitudin sed justo ac, tincidunt hendrerit ante. Sed accumsan dapibus sem, quis aliquam tellus rhoncus eleifend. Nunc at sem sed massa feugiat mattis. Sed imperdiet rutrum dictum. Mauris turpis elit, pretium at imperdiet ac, scelerisque at tortor. Donec laoreet elementum nibh nec lobortis.\n"
"\n"
"Nam varius urna sed ligula pretium, non dictum tellus iaculis. Integer ut velit eget lacus tincidunt consequat. Vivamus et aliquam felis. Ut a nulla tellus. Sed efficitur eu purus at tincidunt. Aliquam luctus pretium congue. Vivamus sit amet ex sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante eu purus interdum finibus id eu mauris. Nunc erat velit, varius vel semper tristique, commodo eget quam. Proin at fringilla orci. Nulla quis viverra magna. Integer sed posuere turpis.\n"
"\n"
"Cras at elementum libero, malesuada semper urna. Fusce accumsan erat ut magna faucibus egestas nec eget elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras lorem nulla, malesuada et neque sit amet, ullamcorper fringilla dui. Aenean fringilla sem in hendrerit convallis. Vivamus lacus orci, cursus ut tellus eu, auctor elementum urna. Vivamus non diam ut nulla blandit tempor. Curabitur vitae aliquam quam. Nunc sollicitudin ipsum enim, a accumsan lorem dictum eget. Donec pellentesque metus id mi maximus efficitur. Nunc quis sapien consectetur arcu tincidunt lacinia a sed felis.\n"
"\n"
"Donec hendrerit eget diam a pellentesque. Nulla mi erat, tincidunt nec turpis vitae, lacinia auctor justo. Phasellus in erat nibh. Quisque suscipit cursus augue, sed semper augue porta ut. Nunc nunc nisl, consequat non condimentum eu, tincidunt quis massa. In at tortor ac enim lobortis viverra eget sed libero. Integer fringilla lorem ligula, vel ultrices lorem efficitur vitae. Phasellus a rutrum leo. Quisque iaculis elit vel ante placerat facilisis. In nec aliquet dui. Praesent augue velit, scelerisque eget ultrices nec, consectetur vitae nisi.\n"
"\n"
"Ut leo enim, sodales sed purus laoreet, convallis suscipit quam. Vivamus placerat sem non nibh venenatis pulvinar. Cras luctus quam in pharetra sodales. Vestibulum venenatis vulputate dui, vel semper lacus condimentum nec. Mauris nec lectus fermentum, consequat augue eu, placerat libero. Pellentesque tempor urna dolor, non commodo est venenatis at. Vestibulum volutpat enim quis viverra pellentesque. Nam rhoncus vel metus id dapibus. Suspendisse suscipit fringilla augue, nec interdum risus gravida ut. Cras vehicula consectetur metus vitae posuere.\n"
"\n"
"Duis a dictum mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed eu placerat tortor, in fringilla nisl. Nunc commodo at magna eget laoreet. Ut porta varius ex, sed aliquet tellus dignissim ut. Nulla rhoncus dolor eget nisl consectetur dictum at et ante. Nam lobortis, magna at faucibus suscipit, lacus magna placerat risus, quis placerat justo neque sed diam. Maecenas cursus arcu maximus magna scelerisque consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam non ante auctor, tincidunt erat sit amet, semper justo. Nullam sagittis suscipit nunc, et eleifend felis ultrices eu. Mauris lacinia porta urna ut laoreet. Fusce convallis justo eros, malesuada faucibus enim auctor in. Morbi convallis lectus nec dui laoreet varius. Integer velit sem, mollis vel facilisis in, fringilla mattis augue.\n"
"\n"
"Quisque at elit nec enim hendrerit cursus. Maecenas elit tellus, elementum in felis vel, efficitur efficitur diam. Ut vel leo at justo euismod tincidunt. Nullam pretium rhoncus sagittis. Nullam lectus tellus, vestibulum ut mi sit amet, ornare viverra purus. Fusce ullamcorper ornare viverra. Donec feugiat, sapien nec euismod bibendum, nunc mi mattis dolor, eu pharetra tellus lorem fringilla odio. Vestibulum lacus turpis, feugiat a libero a, malesuada viverra nulla.\n"
"\n"
"Nam nec pharetra ex, ut pulvinar felis. Ut est purus, volutpat vitae tristique in, mollis at massa. Proin vel suscipit neque. Quisque porttitor eleifend tempor. Cras accumsan neque id elementum porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent at elit odio. Cras in commodo erat. Quisque eget interdum justo. Praesent viverra massa a nisi sodales lacinia quis eu erat. Vestibulum semper placerat mauris pretium scelerisque. Praesent non diam euismod, elementum purus eu, congue leo. Phasellus bibendum purus id luctus euismod. Nunc egestas nunc id augue sollicitudin, a convallis nunc malesuada. Quisque ut ipsum libero. Maecenas rhoncus venenatis dui.\n"
"\n"
"Morbi ullamcorper pretium est commodo ultrices. Pellentesque cursus gravida pellentesque. Ut finibus porta auctor. Aenean vehicula, diam sed luctus vestibulum, augue leo viverra nisl, vitae faucibus lacus leo sit amet massa. Sed scelerisque, neque euismod sodales viverra, nunc felis egestas neque, sed fermentum dolor velit eget dolor. Aliquam at ipsum dapibus, volutpat tellus sit amet, malesuada lacus. Nullam ut tellus in elit dapibus sollicitudin. Ut semper enim sapien, eu mattis lectus luctus ut. Nulla dapibus, purus vel porta interdum, nunc diam consequat felis, in hendrerit felis sapien vitae elit. Curabitur finibus faucibus massa non ornare.\n"
"\n"
"Cras nec mattis neque. Morbi non nulla in sapien condimentum consectetur sit amet nec nisi. Cras interdum nisl sem, et ullamcorper odio tristique ac. Maecenas pharetra diam et orci vestibulum, eget imperdiet leo condimentum. Phasellus mattis urna at nibh rhoncus ultricies. Nullam nulla sem, dictum non efficitur eget, pellentesque nec diam. Nunc tincidunt ut dolor non fermentum. In hac habitasse platea dictumst. Sed laoreet felis id libero lacinia fringilla vitae quis est. Donec enim orci, imperdiet eget leo non, luctus vehicula nunc. Phasellus lorem mauris, convallis non aliquam sed, aliquam nec lacus.\n"
"\n"
"Morbi pretium ante vel interdum ultrices. Aliquam sed dolor at dui vestibulum iaculis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent at ornare mi. Donec at ipsum eget orci ultrices tempus id sit amet mi. Cras id condimentum mauris. Suspendisse potenti. Integer eget suscipit ipsum. Phasellus varius dolor nec tellus congue, quis convallis nunc eleifend.\n"
"\n"
"Sed consequat cursus sem, eu lacinia augue faucibus eget. Donec eu metus ante. Quisque sodales dui in velit elementum gravida. Nullam in est eget odio pellentesque consequat id lacinia felis. Integer ante quam, consequat id elit quis, malesuada efficitur enim. Nunc ultrices tristique nibh, id condimentum nisi commodo non. Vivamus rutrum libero ac leo bibendum, quis condimentum arcu dignissim. Quisque at ipsum at ipsum facilisis pharetra eu nec odio. Proin convallis elit orci, a sagittis turpis ullamcorper ut. Donec pretium tortor ut tellus suscipit ornare tempus ac lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc feugiat mauris sit amet diam tincidunt, nec gravida enim placerat. Morbi ac accumsan diam.\n"
"\n"
"Duis finibus sapien vel eros lacinia, ac aliquet sem volutpat. Curabitur eleifend, purus a auctor consequat, ligula massa efficitur nisl, et pulvinar risus enim eu orci. Suspendisse porttitor bibendum nibh, non ultrices velit. Vivamus luctus ipsum ac tristique malesuada. Quisque luctus nisl erat, sed ullamcorper diam auctor et. Etiam lectus nulla, convallis vitae finibus et, scelerisque ut justo. Etiam dui est, euismod vitae viverra quis, vestibulum et velit. Duis vel nisi sit amet quam iaculis tempus. Aliquam efficitur et eros et consequat.\n"
"\n"
"Quisque tortor velit, elementum a eleifend nec, bibendum in nunc. Fusce elit lorem, imperdiet ut sodales eget, lobortis ultricies elit. Suspendisse ultrices a tellus vel pretium. Mauris egestas posuere risus at bibendum. Sed eu arcu imperdiet, finibus ligula consectetur, rutrum nunc. Curabitur auctor nisl lacus, vitae aliquet augue malesuada sed. In metus eros, mattis in lorem nec, placerat vulputate urna. In eu ligula ultricies, rutrum quam tristique, condimentum massa. Quisque rhoncus consequat ante eu mattis. Aliquam cursus arcu at metus hendrerit, eu finibus magna molestie. Donec consectetur nunc nec sagittis porttitor. Suspendisse potenti. Donec malesuada sem quis diam tristique, viverra consectetur ante pretium. Nullam varius justo a est hendrerit, eu rhoncus eros semper.\n"
"\n"
"Vivamus turpis diam, eleifend in augue ut, placerat faucibus turpis. Nunc aliquam, sem eu efficitur dignissim, velit sapien volutpat turpis, nec posuere ligula tortor ut ipsum. Quisque viverra ex eu scelerisque bibendum. Etiam lobortis est ac elementum volutpat. Fusce turpis sem, hendrerit non lobortis et, mollis a dui. Cras vel risus tincidunt est bibendum pulvinar quis eget lorem. Aliquam bibendum blandit molestie. Etiam nec interdum odio, vel vestibulum arcu. Fusce tempor mi id mauris placerat, non sollicitudin odio aliquet. Nam malesuada suscipit tortor, quis sollicitudin sapien volutpat a. Etiam dignissim volutpat erat, in commodo tellus tempor in. Vivamus urna enim, consequat vel nibh euismod, placerat laoreet tortor. Maecenas in molestie augue, nec gravida sem. Vivamus in mollis mauris. Sed feugiat neque eu odio euismod, sit amet sodales est iaculis. Mauris non pellentesque augue.\n"
"\n"
"Pellentesque augue purus, semper ac scelerisque vel, volutpat eu mi. Quisque tincidunt rutrum lorem, id porttitor nulla eleifend mattis. Integer nec est quis felis mattis elementum eget id velit. Nulla nec felis vitae arcu tincidunt convallis quis vel eros. Sed rhoncus semper magna, sed sollicitudin ex facilisis eu. Morbi commodo, metus et gravida bibendum, leo tellus facilisis leo, commodo eleifend libero odio lacinia odio. Fusce vel lacus risus. Nullam est arcu, suscipit eget mattis ac, viverra non orci.\n"
"\n"
"In faucibus lorem fringilla metus cursus, ac efficitur neque varius. Donec diam sem, blandit ac orci pretium, ultricies pharetra tellus. Mauris pharetra blandit ligula. Suspendisse varius, nisi sit amet ultrices lacinia, augue nisl cursus libero, eget venenatis urna ante eu ex. Duis ut purus porta dui convallis blandit. Vivamus mollis facilisis mi, quis imperdiet sem malesuada eu. Sed leo arcu, suscipit non mi sit amet, auctor tempor tellus. Suspendisse id viverra risus.\n"
"\n"
"Aenean in ullamcorper dui. Integer sollicitudin commodo lectus, quis consequat velit commodo id. Vestibulum auctor eros quis nisl faucibus, varius congue mi sollicitudin. Vivamus auctor libero ut nulla lobortis gravida. Praesent et ornare orci. Pellentesque ut viverra odio. In hac habitasse platea dictumst. Sed quis libero ac arcu ultrices molestie. Sed fermentum arcu ante, eget elementum metus feugiat non. Donec ornare egestas tellus quis elementum. Maecenas quis commodo tortor. Donec sodales commodo leo, vitae elementum risus dignissim vel. Phasellus at sapien vitae nisl molestie blandit. Nulla ultrices dapibus dignissim. Vivamus at ex eu dolor faucibus iaculis. Cras congue bibendum risus at rhoncus.\n"
"\n"
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis sit amet quam magna. In ut sagittis est. Mauris sit amet sem sed nulla dictum varius sit amet vitae nisl. Phasellus scelerisque pharetra tristique. Mauris in euismod libero. Morbi suscipit egestas nisl nec sollicitudin. Fusce dapibus, urna ut varius dignissim, tellus ligula auctor nulla, ac semper eros felis sodales mauris. Donec quis mollis magna. Phasellus accumsan ligula nec lacus hendrerit, quis bibendum quam ullamcorper. Proin egestas cursus egestas. Cras varius sapien mauris, et sollicitudin libero tempus ut. Fusce aliquam nisi in feugiat facilisis. Ut mattis luctus mattis.\n"
"\n"
"Maecenas in diam rhoncus, luctus nisl nec, scelerisque magna. Aliquam vulputate orci magna, a suscipit neque ultrices eget. Praesent sodales pharetra mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque accumsan porta interdum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In gravida tempus semper. Nullam at lectus eget justo maximus viverra vitae quis lectus. Nullam nulla libero, sodales eu libero ut, posuere tempor turpis.\n"
"\n"
"Suspendisse at velit at nibh tristique eleifend sit amet sed elit. Nam diam lacus, varius eget scelerisque in, volutpat et leo. Pellentesque nec laoreet eros. Nullam imperdiet tellus nec lorem faucibus ullamcorper. Suspendisse tincidunt vulputate dignissim. Nullam pharetra libero turpis, gravida efficitur augue euismod eu. Aenean dui ipsum, cursus eget pulvinar pharetra, condimentum sed libero. Aenean diam nisl, imperdiet eu faucibus eu, faucibus non eros. Mauris eu nulla rutrum, consequat urna ac, auctor leo. Cras luctus, odio eget suscipit fermentum, elit orci facilisis ex, gravida tempor lacus augue sit amet libero. Suspendisse posuere ante sit amet tellus condimentum vestibulum. Aliquam efficitur, lectus vitae interdum scelerisque, neque libero blandit velit, sed placerat ipsum est non erat. Duis eleifend iaculis ultrices. Proin pharetra neque interdum, volutpat risus hendrerit, varius ante.\n"
"\n"
"Ut dignissim vulputate nulla dapibus dapibus. Praesent dapibus nisi vitae diam egestas gravida. Vestibulum quis justo mattis, fermentum quam eget, porta nunc. Nunc elit libero, ultrices ut ante at, maximus imperdiet enim. Suspendisse malesuada, arcu non ornare scelerisque, orci quam hendrerit lacus, nec maximus neque ante a magna. Quisque pulvinar maximus nisi eget iaculis. Vivamus sed sem at nulla dignissim posuere id at purus. Pellentesque ultricies leo ut sagittis suscipit. Morbi id eros lobortis, pellentesque neque ut, efficitur lorem. Ut ac elit tincidunt, blandit felis in, ultricies libero. Fusce vel egestas mi.\n"
"\n"
"Sed eget lorem tincidunt, dapibus metus sed, luctus erat. Phasellus eget arcu nec libero volutpat sollicitudin ac id justo. Aliquam non facilisis tellus. Fusce dictum, leo a efficitur ultrices, dolor magna ullamcorper elit, eu vulputate felis leo in tellus. Nulla cursus urna molestie, sodales elit non, ultrices mi. Nulla feugiat ex id consequat aliquet. In volutpat nunc tortor, vitae sagittis lacus pellentesque finibus. Donec a libero quis purus sodales viverra. Nam id urna a.";

// C strcmp implementation
int strcmp(const char* str1, const char* str2) {
    while (1) {
        if (*str1 > *str2) {
            return 1;
        }
        else {
            if (*str1 < *str2) {
                return -1;
            }
            // *str1 == *str2
            else {
                if (*str1 == 0) {
                    return 0;
                }
            }
        }

        str1++;
        str2++;
    }
}

void _start() {
    if (strcmp(lorem1, lorem2) == 0) {
        prints(success_msg);
        sys_exit(33);
    }
    else {
        prints(error_msg);
        sys_exit(1);
    }
}
